version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: deploy/php/Dockerfile
    container_name: app
    user: "1000:1000"
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ../project:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      - ../project:/var/www/html
    depends_on:
      - app
      - db
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    container_name: db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: nette
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
