services:
  app:
    build:
      context: ..
      dockerfile: deploy/php/Dockerfile
    image: app
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "9000"
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: db
    env_file:
      - ../project/.env
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ../project:/var/www/html
      - ./nginx/default.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - db
    networks:
      - app-network

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: "nette"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge